kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat-app-deploy
  namespace: chat-app-demo
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
      tier: frontend
  template:
    metadata:
      labels:
        app: chat-app
        tier: frontend
    spec:
      containers:
        - name: spring
          image: chat-app-demo
          ports:
            - name: chat-app
              containerPort: 8080
              protocol: TCP
          env:
            - name: REDIS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-cm
                  key: url
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%