kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: chat-app-hpa
  namespace: chat-app-demo
spec:
  scaleTargetRef:
    kind: Deployment
    name: chat-app-deploy
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50